site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs
extra_css: [extra.css]

nav:
- Home: 'index.md'
- Getting started:
  - 'Introduction': 'getting_started/introduction.md'
  - 'Quick start': 'getting_started/quickstart.md'
- Building CARLA:
  - 'Linux build': 'how_to_build_on_linux.md'
  - 'Windows build': 'how_to_build_on_windows.md'
  - 'Update CARLA': 'update_carla.md'
  - 'Build system': 'dev/build_system.md'
  - 'Running in a Docker': 'carla_docker.md'
  - 'F.A.Q.': 'faq.md'
- First steps:
  - 'Core concepts': 'core_concepts.md'
  - '1st. World and client': 'core_world.md'
  - '2nd. Actors and blueprints': 'core_actors.md'
  - '3rd. Maps and navigation': 'core_map.md'
  - '4th. Sensors and data': 'core_sensors.md'
- Advanced steps:
  - 'Recorder': 'recorder_and_playback.md'
  - 'Rendering options': 'rendering_options.md'
  - 'Synchrony and time-step': 'simulation_time_and_synchrony.md'
- References:
  - 'Python API reference': 'python_api.md'
  - 'Code recipes': 'python_cookbook.md'
  - 'Blueprint Library': 'bp_library.md'
  - 'C++ reference' : 'cpp_reference.md'
  - 'Recorder binary file format': 'recorder_binary_file_format.md'
  - "Sensors reference": 'ref_sensors.md'  
- How to... (general):
  - 'Add a new sensor': 'dev/how_to_add_a_new_sensor.md'
  - 'Add friction triggers': "how_to_add_friction_triggers.md"
  - 'Control vehicle physics': "how_to_control_vehicle_physics.md"
  - 'Control walker skeletons': "walker_bone_control.md"
  - 'Creating standalone asset packages for distribution': 'asset_packages_for_dist.md'
  - 'Generate pedestrian navigation': 'how_to_generate_pedestrians_navigation.md'
  - "Link Epic's Automotive Materials": 'epic_automotive_materials.md'
  - 'Map customization': 'dev/map_customization.md'
- How to... (content):
  - 'Add assets': 'how_to_add_assets.md'
  - 'Create and import a new map': 'how_to_make_a_new_map.md'
  - 'Model vehicles': 'how_to_model_vehicles.md'
- ROS bridge:
  - 'ROS bridge installation': 'ros_installation.md'
  - 'Messages reference': 'ros_msgs.md'
  - 'Launch reference': 'ros_launchs.md'
  #- 'Supported features': 'ros_topics_ref.md'
- Contributing:
  - 'Contribution guidelines': 'CONTRIBUTING.md'
  - 'Coding standard': 'coding_standard.md'
  - 'Documentation standard': 'doc_standard.md'
  - 'Make a release': 'dev/how_to_make_a_release.md'
  - 'Upgrade the content': 'dev/how_to_upgrade_content.md'
  - 'Code of conduct': 'CODE_OF_CONDUCT.md'

markdown_extensions:
  - admonition
